apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  labels:
  {{- include "enbuild-helm-chart.labels" . | nindent 4 }}
type: Opaque
data:
  ENVIRONMENT: cHJvZAo=
  {{- if eq (printf "%s" .Values.global.auth_plugin | lower) "local" }}
  IS_LOCAL: {{ (printf "true" | b64enc ) }}
  {{- end }}
  {{- if .Values.global.disable_tls_gitlab }}
  NODE_TLS_REJECT_UNAUTHORIZED: {{ (printf "0" | b64enc ) }}
  {{- end }}
stringData:
  ENCRYPTION_KEY: "{{.Values.enbuildBk.encryption_key}}"
  OPENAI_API_KEY: "{{.Values.enbuildGenAI.api_key}}"
  # AUTH_MECHANISM: "{{ (printf "%s" .Values.global.auth_plugin | upper) }}"
  # {{- if eq (printf "%s" .Values.global.auth_plugin | lower) "keycloak" }}
  # KEYCLOAK_BACKEND_URL: "{{.Values.global.keycloak.keycloak_url}}"
  # KEYCLOAK_BACKEND_SECRET: "{{.Values.global.keycloak.keycloak_backend_secret}}"
  # KEYCLOAK_BACKEND_USERNAME: "{{.Values.global.keycloak.keycloak_backend_username}}"
  # KEYCLOAK_BACKEND_PASSWORD: "{{.Values.global.keycloak.keycloak_backend_password}}"
  # KEYCLOAK_REALM: "{{.Values.global.keycloak.keycloak_realm}}"
  # {{- end }}
  # {{- if eq (printf "%s" .Values.global.auth_plugin | lower) "okta" }}
  # OKTA_CLIENT_URL: "{{ .Values.global.okta.client_url }}"
  # OKTA_CLIENT_SECRET: "{{ .Values.global.okta.client_secret }}"
  # OKTA_CLIENT_ID: "{{ .Values.global.okta.client_id }}"
  # OKTA_BASE_URL: "{{ .Values.global.okta.base_url }}"
  # OKTA_CLIENT_TOKEN: "{{ .Values.global.okta.client_token }}"
  # {{- end }}
  {{- if .Values.rabbitmq.enabled }}
  RABBIT_MQ_CONNECTION_STRING: amqp://{{.Values.rabbitmq.auth.username}}:{{.Values.rabbitmq.auth.password}}@{{ .Release.Name }}-rabbitmq:5672/
  {{- else }}
  RABBIT_MQ_CONNECTION_STRING: amqp://{{.Values.rabbitmq.auth.username}}:{{.Values.rabbitmq.auth.password}}@{{.Values.rabbitmq.host}}:5672/
  {{- end }}
  RABBIT_MQ_ENV: "{{ .Values.rabbitmq.env }}"
  RABBITMQ_QUEUE_PREFIX: "{{ .Values.rabbitmq.queue_prefix }}"

  {{- if .Values.enbuildConsumer.gitlab }}
  GITLAB_HOST: "{{ .Values.enbuildConsumer.gitlab.host }}"
  GITLAB_TOKEN: "{{ .Values.enbuildConsumer.gitlab.token }}"
  GITLAB_GROUP: "{{ .Values.enbuildConsumer.gitlab.gitlab_group }}"
  GITLAB_PROJECT_ID: "{{ .Values.enbuildConsumer.gitlab.gitlab_project_id }}"
  GITLAB_NAMESPACE_ID: "{{ .Values.enbuildConsumer.gitlab.gitlab_namespace_id }}"
  GITLAB_TOKEN_NAME: "{{ .Values.enbuildConsumer.gitlab.gitlab_token_name }}"
  GITLAB_REF: "{{ .Values.enbuildConsumer.gitlab.gitlab_ref }}"
  {{- end }}
  {{- if .Values.enbuildConsumer.github }}
  GITHUB_HOST: "{{ .Values.enbuildConsumer.github.host }}"
  GITHUB_HOST_URL: "{{ .Values.enbuildConsumer.github.hosturl }}"
  GITHUB_ACCOUNT: "{{ .Values.enbuildConsumer.github.github_account }}"
  GITHUB_TOKEN: "{{ .Values.enbuildConsumer.github.token }}"
  GITHUB_BRANCH: "{{ .Values.enbuildConsumer.github.branch }}"
  GITHUB_HOST_GQL_URL: "{{ .Values.enbuildConsumer.github.hostgql}}"
  GITHUB_MANIFEST_URL: "{{ .Values.enbuildConsumer.github.manifest_host }}"
  GITHUB_MANIFEST_ACCOUNT: "{{ .Values.enbuildConsumer.github.manifest_github_account }}"
  GITHUB_MANIFEST_REPO: "{{ .Values.enbuildConsumer.github.manifest_repo }}"
  GITHUB_MANIFEST_TOKEN: "{{ .Values.enbuildConsumer.github.manifest_token }}"
  GITHUB_MANIFEST_REF: "{{ .Values.enbuildConsumer.github.manifest_branch }}"
  GITHUB_MANIFEST_BRANCH: "{{ .Values.enbuildConsumer.github.manifest_branch }}"
    {{- if .Values.enbuildConsumer.github.github_es  }}
  IS_GITHUB_ES: "{{ .Values.enbuildConsumer.github.github_es }}"
  {{- end }}
  {{- end }}