apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-enbuild-mq
  labels:
    app: mq
    app.kubernetes.io/component: mq
  {{- include "enbuild-helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.enbuildSync.replicas }}
  selector:
    matchLabels:
      app: mq
      app.kubernetes.io/component: mq
    {{- include "enbuild-helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mq
        app.kubernetes.io/component: mq
      {{- include "enbuild-helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MONGODB_ENDPOINT
          value: mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@$(MONGO_SERVER)
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-mongo-secrets
        - secretRef:
            name: {{ .Release.Name }}-backend-secret
        image: {{ .Values.enbuildSync.image.repository }}:{{ .Values.enbuildSync.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.enbuildSync.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 3
          exec:
            command:
            - node
            - src/queue/testConnection.js
          initialDelaySeconds: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        # readinessProbe:
        #   failureThreshold: 3
        #   initialDelaySeconds: 3
        #   periodSeconds: 60
        #   successThreshold: 1
        #   timeoutSeconds: 10
          exec:
            command:
            - node
            - src/queue/testConnection.js
        name: enbuild-mq
        args:
          - run
          - run:mq:all
        command:
          - npm
        # ports:
        # - containerPort: 8080
        resources: {{- toYaml .Values.enbuildSync.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
{{- if .Values.imageCredentials }} 
      imagePullSecrets:
        - name: {{ .Release.Name }}-image-pull-secret
{{- end }}
---
