apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo-secrets
  labels:
  {{- include "enbuild-helm-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "{{.Values.mongodb.mongo_root_username}}"
  MONGO_INITDB_ROOT_PASSWORD: "{{.Values.mongodb.mongo_root_password}}"
  MONGO_INITDB_DATABASE: enbuild
  {{ if .Values.mongodb.enabled }}
  MONGO_SERVER: "{{ .Release.Name }}-mongo.{{ .Release.Namespace }}.svc.cluster.local:27017"
  {{ else }}
  MONGO_SERVER: "{{.Values.mongodb.mongo_server}}"
{{ end }}
  
