apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-conf
  labels:
{{- include "enbuild-helm-chart.labels" . | nindent 4 }}
data:
  default.conf: |-
    server {
      listen 8080 default_server;
      server_name _;
      proxy_pass_header Authorization;
      proxy_set_header Host $host;

      location /enbuild-bk/ {
        proxy_pass http://{{ .Release.Name }}-enbuild-backend/;
      }

      location /enbuild-user/ {
        proxy_pass http://{{ .Release.Name }}-enbuild-user/;
      }

{{- if .Values.enbuildMl.enabled }}

      location /enbuild-ml/ {
        proxy_pass http://{{ .Release.Name }}-enbuild-ml/;
      }
      {{- if .Values.jupyterhub.cull.enabled }}
      location /jupyter/ {
          proxy_pass http://proxy-public/jupyter/;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_redirect /hub/ /jupyter/hub/;
          proxy_cookie_path /hub/ /jupyter/hub/;
          sub_filter 'href="/hub/' 'href="/jupyter/hub/';
          sub_filter 'src="/hub/' 'src="/jupyter/hub/';
          sub_filter_once off;
      }
      {{- end }}
{{- end }}

{{- if .Values.enbuildGenAI.enabled }}

      location /enbuild-genai/ {
        proxy_pass http://{{ .Release.Name }}-enbuild-genai/;
      }
{{- end }}

{{- if .Values.enbuildAI.enabled }}

      location /enbuild-ai/ {
        proxy_pass http://{{ .Release.Name }}-enbuild-ai/;
      }
{{- end }}
    }