{{- if and .Values.jupyterhub.cull.enabled (.Values.global.istio.enabled ) (not .Values.global.ingress.enabled ) -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-jupyter
  labels:
  {{- include "enbuild-helm-chart.labels" . | nindent 4 }}
spec:
  gateways:
  - {{ .Values.global.istio.gateway }}
  hosts:
  - jupyter.{{ .Values.global.domain }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: proxy-public
        port:
          number: 80
{{- end }}
