apiVersion: v2
name: enbuild
description: A Helm chart for ENBUILD
type: application
keywords: [enbuild, bigbang]
home: https://www.vivsoft.io/
sources: [https://github.com/jupyterhub/zero-to-jupyterhub-k8s]
icon: https://github.com/vivsoftorg/docs-enbuild/blob/main/assets/cover.png
kubeVersion: '>=1.25.0-0'
version: 0.0.3
appVersion: 1.0.8
maintainers:
  - name: Juned Memon
    email: jmemon@vivsoft.io
dependencies:
  - name: rabbitmq
    version: 11.13.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: jupyterhub
    version: 2.0.0
    repository: https://jupyterhub.github.io/helm-chart
    condition: jupyterhub.cull.enabled
