
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: enbuild-chart-hauler
spec:
  charts:
    - name: enbuild
      repoURL: https://vivsoftorg.github.io/enbuild
      version: 0.0.20
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: enbuild-images-hauler 
spec:
  images:
    - name: docker.io/bitnami/rabbitmq:3.11.13-debian-11-r0
      platform: linux/amd64
    - name: registry.gitlab.com/enbuild-staging/vivsoft-platform-ui/enbuild-backend:1.0.16
      platform: linux/amd64
    - name: registry.gitlab.com/enbuild-staging/vivsoft-platform-ui/enbuild-frontend:1.0.16
      platform: linux/amd64
    - name: registry.gitlab.com/enbuild-staging/vivsoft-platform-ui/enbuild-mq-consumer:1.0.16
      platform: linux/amd64
    - name: registry.gitlab.com/enbuild-staging/vivsoft-platform-ui/enbuild-user:1.0.16
      platform: linux/amd64
    - name: registry.gitlab.com/enbuild-staging/vivsoft-platform-ui/mongodb:4.4.5
      platform: linux/amd64
    
