version: 1
project_name: enbuild
before:
  hooks:
    - go mod tidy
    - go mod download
    - rm -rf binaries

release:
  prerelease: auto

env:
  - yq_version=v4.44.1
  - GO111MODULE=on
  - vpkg="0.0.1"

builds:
  - main: main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # ldflags:
    #   - -s -w -X {{ .Env.vpkg }}.gitVersion={{ .Version }} -X {{ .Env.vpkg }}.gitCommit={{ .ShortCommit }} -X {{ .Env.vpkg }}.gitTreeState={{if .IsGitDirty}}dirty{{else}}clean{{end}} -X {{ .Env.vpkg }}.buildDate={{ .Date }}
    hooks:
      pre:
        - mkdir -p binaries
        - wget -P cmd/enbuild/binaries/ https://github.com/mikefarah/yq/releases/download/{{ .Env.yq_version }}/yq-{{ .Os }}-{{ .Arch }}{{ if eq .Os "windows" }}.exe{{ end }}
      post:
        - rm -rf binaries
    env:
      - CGO_ENABLED=0

universal_binaries:
  - replace: false

changelog:
  skip: true
  use: git