[[main]]
  name = "GitHub"
  url = "https://github.com/vivsoftorg/enbuild"
  weight = 10

[[social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/VivSoft/"
  weight = 20

[[social]]
  name = "Twitter"
  url = "https://twitter.com/VivSoft"
  weight = 30
