global:
  image:
    registry: registry.gitlab.com
    pullPolicy: IfNotPresent
    registry_credentials: {}
      # username: registry_user_name
      # password: registry_password
  domain: ijuned.com         # Set the proper doamin.
  ingress:
    enabled: true
    tls: true
    tls_secret: vivplatform-cert
    classname: nginx
    annotations:
      cert-manager.io/cluster-issuer: "selfsigned"