name: Release Latest
on:
  push:
    branches: [main]
    paths:
      - "cli/**"
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.21.x

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: 1.26.2
          workdir: cli
          distribution: goreleaser
          args: release --rm-dist --skip-publish --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}