name: Release Cli
on:
  push:
    branches:
      - main
    paths:
      - "cli/**"
jobs:
  go-release:
    name: Go Release Job
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Run Go Releaser
        uses: goreleaser/goreleaser-action@v5
        with:
          workdir: cli
          distribution: goreleaser
          version: latest
          args: release --clean -p 1 --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: v0.0.2  # Hack to bypass the semver issue
          GORELEASER_PREVIOUS_TAG: v0.0.1 # Hack to bypass the semver issue