name: Release Cli

on:
  push:
    tags:         # Trigger only on tags
      - 'v*'      # Ensure this matches your versioning scheme (e.g., v0.0.7)
    branches:
      - main
    paths:
      - "cli/**"

jobs:
  go-release:
    name: Go Release Job
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Run Go Releaser
        uses: goreleaser/goreleaser-action@v5
        with:
          workdir: cli
          distribution: goreleaser
          version: latest
          args: release --clean -p 1 --skip=validate --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GORELEASER_CURRENT_TAG: ${{ github.ref_name }}  # Use the current tag from the event context
      #     GORELEASER_PREVIOUS_TAG: ${{ steps.previous_tag.outputs.previous-tag }}

      # - name: Get Previous Tag
      #   id: previous_tag
      #   run: echo "::set-output name=previous-tag::$(git describe --tags --abbrev=0 HEAD^)"