name: Release Cli

on:
  push:
    tags:         # Trigger only on tags
      - 'v*'      # Ensure this matches your versioning scheme (e.g., v0.0.7)
    paths:
      - "cli/**"

jobs:
  go-release:
    name: Go Release Job
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Set tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Run Go Releaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: 1.26.2
          workdir: cli
          distribution: goreleaser
          args: release --clean -p 1 --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GORELEASER_CURRENT_TAG: ${{ github.ref_name }}  # Use the current tag from the event context
      #     GORELEASER_PREVIOUS_TAG: ${{ steps.previous_tag.outputs.previous-tag }}