name: Create Haul
on:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout code repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.CR_TOKEN }}"

      # Set up Python environment and install dependencies
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install ruamel-yaml semver

      # Configure Git for committing changes
      - name: Configure Git
        run: |
          git config user.name "junaid18183"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # Get the current version using a custom script
      - name: Get Current Version
        id: get_current_var
        run: echo "current_version=$(.github/scripts/update_versions.py get_chart_version)" >> $GITHUB_OUTPUT

      # Add necessary Helm repositories
      - name: Add Helm Repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add jupyterhub https://jupyterhub.github.io/helm-chart
          helm repo add open-webui https://helm.openwebui.com/
          helm repo add loki-stack https://grafana.github.io/helm-charts

      # Create the haul file, sync with server, and save it
      - name: Create and Save Haul File
        id: generate-haul-file
        run: |
          cd charts/enbuild 
          helm dependency build
          cd ../../
          .github/scripts/create_haul_file.sh ${{ steps.get_current_var.outputs.current_version }} charts/enbuild
          /usr/local/bin/hauler store sync -f "/tmp/enbuild_${{ steps.get_current_var.outputs.current_version }}_haul.yaml"
          /usr/local/bin/hauler store save --filename enbuild-${{ steps.get_current_var.outputs.current_version }}.tar.zst

      # Upload the resulting file to AWS S3
      - name: Upload to S3
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: enbuild-${{ steps.get_current_var.outputs.current_version }}.tar.zst
          destination: s3://enbuild-haul/enbuild-${{ steps.get_current_var.outputs.current_version }}.tar.zst
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_DEFAULT_REGION }}
