name: Create Haul
on:
  push:
    branches:
      - dev
    # paths:
    #   - "charts/**"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.CR_TOKEN }}"

      - name: Prepare Environment
        run: pip3 install ruamel-yaml semver

      - name: Configure Git
        run: |
          git config user.name "junaid18183"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get current version
        id: get_current_var
        run: echo "current_version=$(.github/scripts/update_versions.py get_chart_version)" >> $GITHUB_OUTPUT

      - name: Add repo
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add jupyterhub https://jupyterhub.github.io/helm-chart
          helm repo add open-webui https://helm.openwebui.com/
          helm repo add loki-stack https://grafana.github.io/helm-charts

      - name: Create Haul
        id: generate-haul-file
        run: |
          cd charts/enbuild 
          helm dependency build
          cd ../../
          .github/scripts/create_haul_file.sh ${{ steps.get_current_var.outputs.current_version }} charts/enbuild
          echo "Syncing the Hauler file with the Hauler server"
          /usr/local/bin/hauler store sync -f "/tmp/enbuild_${{ steps.get_current_var.outputs.current_version }}_haul.yaml"
          echo "Saving the Hauler tar.zst file"
          /usr/local/bin/hauler store save --filename //tmp/enbuild-${{ steps.get_current_var.outputs.current_version }}-haul.tar.zst
        artifacts:
          paths:
            - /tmp/enbuild-${{ steps.get_current_var.outputs.current_version }}-haul.tar.zst

      - uses: keithweaver/aws-s3-github-action@v1.0.0
        needs: generate-haul-file
        with:
          command: cp
          source: /tmp/enbuild-${{ steps.get_current_var.outputs.current_version }}-haul.tar.zst
          destination: s3://enbuild-haul/enbuild-${{ steps.get_current_var.outputs.current_version }}-haul.tar.zst
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_DEFAULT_REGION }}
#-----------------------------------------------------------------------------------------------------------------------------------------------------